# repo = "helix-editor/helix"
# remote-branch = "master"
repo = "helix-editor/helix"
remote-branch = "master"
local-branch = "patchy"

pull-requests = [
  # "8675", # steel
  "11497", # Rounded corners
  # "12369", # Icons
  # "12022", # JJ diff provider
  # "14118", # indent guides
  # "13133", # Inline git blame # Merge conflicts
  # "12520", # Picker title # Patchy conflicts
  # "13963", # Automatic reload when file changes externally
]

branches = []
patches = []
